# typos is a Source code spell checker
# https://github.com/crate-ci/typos
[default.extend-words]
# biome.json uses noInferrableTypes
inferrable = "inferrable"

[files]
extend-exclude = ["dist", "node_modules", "vendor", "coverage", "build", "dist"]
