name: 'happy-commit'
description: 'Celebrate pull-request when it contains a lucky commit'

branding:
  icon: award
  color: yellow

inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  additional_rules:
    description: 'Additional rules to check'
    required: false

runs:
  # We should use node18, but it seems that it is not supported yet
  # tsconfig.json has target es2016, so it should work properly with node16
  # https://json.schemastore.org/github-action.json
  # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
  using: 'node16'
  main: 'dist/index.js'
