name: 'happy-commit'
description: 'Celebrate pull-request when it contais a lucky commit'

branding:
  icon: award
  color: yellow

inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  additional_rules:
    description: 'Additional rules to check'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
