name: Example
on:
  - pull_request

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  example:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    name: dogfooding
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          additional_rules: |
            [
              {
                "kind": "pr",
                "rule": ".+",
                "message": "dogfooding: PR #{{prNum}} always celebrates."
              },
              {
                "kind": "commit",
                "rule": "[0-9a-f]",
                "message": "dogfooding: `{{commitId}}` always celebrates."
              }
            ]
