name: Example
on:
  - pull_request

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  example:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    name: dogfooding
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          additional_rules: |
            [
              {
                "kind": "commit",
                "rule": "(?:1)",
                "message": "custom message! `{{commitId}}` is lucky! It contains {{matched}}"
              }
            ]
